CREATE USER IF NOT EXISTS IPL_APP PASSWORD 'SWENG_500';
ALTER USER IPL_APP ADMIN TRUE;
CREATE SCHEMA SWENG500;

CREATE TABLE SWENG500.USERS
(
	ID IDENTITY NOT NULL PRIMARY KEY,
	FIRSTNAME NVARCHAR(50),
	LASTNAME NVARCHAR(50),
	NICKNAME NVARCHAR(50),
	EMAILADDRESS NVARCHAR(50) NOT NULL,
	GENDER NVARCHAR(50),
	PASSWORD NVARCHAR(256)
);

CREATE TABLE SWENG500.USERMEASUREMENTS
(
	USERID BIGINT REFERENCES SWENG500.USERS (ID),
	MEASUREMENTDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	HEIGHT NUMERIC (5,2) NOT NULL,
	WEIGHT NUMERIC (5,2) NOT NULL,
	WASIT NUMERIC (5,2) NOT NULL,
	NECK NUMERIC (5,2) NOT NULL,
	HIP NUMERIC (5,2),
	WRIST NUMERIC (5,2),
	FOREARM NUMERIC (5,2)
);

CREATE TABLE SWENG500.WORKOUTS
(
	ID IDENTITY NOT NULL PRIMARY KEY,
	USERID BIGINT REFERENCES SWENG500.USERS (ID),
	DESCRIPTION NVARCHAR(510),
	WORKOUTDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE SWENG500.WORKOUTSETS
(
	ID IDENTITY NOT NULL PRIMARY KEY,
	WORKOUTID BIGINT REFERENCES SWENG500.WORKOUTS (ID),
	SETNUMBER INT,
	REPCOUNT INT,
	EXERCISENAME NVARCHAR(50),
	PARTOFTOTAL BOOLEAN,
	WEIGHTLIFTED NUMERIC(5, 2)
);